### ISSUE TITLE
Can you send a `typia` PR about your setup guidance?

### ISSUE THREAD

**Issue by samchon** [ryoppippi/unplugin-typia#1]
https://github.com/samchon/typia/blob/master/website/pages/docs/setup.mdx

As I'm not developing frontend, I don't know enough about frontends to give an installation guide.

This repo seems guiding clear solution of it, so that I hope your description to the setup documents of `typia`.

**Comment by ryoppippi** [comment]
OK! Thanks!
I'll do that

**Comment by ryoppippi** [comment]
@samchon 
I'm considering transferring this repo to the official unplugin org.
So please wait!

https://github.com/unplugin/.github/issues?q=is:issue+is:open+sort:updated-desc

**Comment by ryoppippi** [comment]
An alternative would be to place this codebase under the control of typia.
In that case, it might be easier to create a typia organisation on github to manage it!
@samchon

**Comment by ryoppippi** [comment]
OK I'll write a doc for current config

**Comment by ryoppippi** [comment]
done with https://github.com/samchon/typia/pull/1074
