### ISSUE TITLE
Not generated when ran with esbuild and Github Action

### ISSUE THREAD

**Issue by slainless** [ryoppippi/unplugin-typia#163]
Checkout: https://github.com/slainless/prodeskel-ws/blob/master/.github/workflows/jsr.yml

Not generated in JSR build: 
https://jsr.io/@slainless/prodeskel-ws/0.1.3/dist/core/index.js#L20
Compared to:
https://github.com/slainless/prodeskel-ws/blob/master/src/core/index.ts#L31

Summary:
- Using Bun as runtime
- Building using esbuild + plugin
- Working as expected on local machine, freshly cloned & following the steps in jsr.yml 1 to 1.

**Comment by ryoppippi** [comment]
OK, it does not work on my env too.
Hmm let me check

**Comment by ryoppippi** [comment]
idk, but this project is too complex.
Why you have so many `tsconfig.json`.

I also added `tsconfig` options to `unplugin-typia` instance, but not works.
`tsc` and `typia generate` works fine.

idk

**Comment by ryoppippi** [comment]
idk why it is not works for `esbuild`, but when I tested with `bun build` script, it works.

If you really want to use `esbuild`, you can keep this issue.

Otherwise, use this script instead

```ts
import dts from 'bun-plugin-dts-auto'
import UnpluginTypia from '@ryoppippi/unplugin-typia/bun'
import {$} from 'bun'

await $`rm -rf dist`

await Bun.build({
	entrypoints: [
	  "./src/core/index.ts",
    "./src/schema/index.ts",
    "./src/browser/index.ts"
	],
	outdir: "./dist",
  splitting:true,
  target: "browser",
	plugins: [
    UnpluginTypia({ cache: false }),
    dts()
	]
});
```

**Comment by ryoppippi** [comment]
idk why it is not works for `esbuild`, but when I tested with `bun build` script, it works.

If you really want to use `esbuild`, you can keep this issue.

Otherwise, use this script instead

```ts
import dts from 'bun-plugin-dts-auto'
import UnpluginTypia from '@ryoppippi/unplugin-typia/bun'
import { $ } from 'bun'

await $`rm -rf dist`

const pkgJSON = await Bun.file('./package.json').json()
const dependencies = [
  ...Object.keys(pkgJSON.dependencies || {}),
  ...Object.keys(pkgJSON.devDependencies || {})
]

await Bun.build({
  entrypoints: [
    "./src/core/index.ts",
    "./src/schema/index.ts",
    "./src/browser/index.ts"
  ],
  outdir: "./dist",
  splitting:true,
  target: "browser",
  external: dependencies,
  plugins: [
    UnpluginTypia({ cache: true, log: 'verbose' }), // you can choose wheather you use cache or not
    dts()
  ]
});
```

**Comment by ryoppippi** [comment]
Also, it is better if you use Bun's official GitHub Actions https://bun.sh/guides/runtime/cicd

**Comment by slainless** [comment]
> idk why it is not works for `esbuild`, but when I tested with `bun build` script, it works.

Actually, I have also tested doing the bundling via Bun and it's generated as expected.
So my guess, it's either:
- A bug in unjs unplugin implementation for esbuild
- A bug in esbuild

But it's still an early guess since I haven't tried using other bundler or reproducing this issue in simpler repository to prove esbuild + unplugin-typia combination to be not working as expected.

Anyway, thanks for the response. Will switch out from esbuild for the time being.

**Comment by ryoppippi** [comment]
@slainless 
Hi!
I updated some dependencies, I released a new version of `unplugin-typia` and `typia`

Have you ever tested? Is build result same?

**Comment by ryoppippi** [comment]
@slainless If you need any further support, please open this issue

**Comment by ryoppippi** [comment]
hi @slainless 
I faced your issue with esbuild today.

I think it's because the order of the esubild plugins is messed up
There is no `enforce` option like rollup/vite, so it is possible that unplugin-typia is being executed after typescript type information is lost.

**Comment by slainless** [comment]
Local environment or Github? Weird that I cant reproduce it in my local env back then. Haven't really tried it again with esbuild though...

**Comment by ryoppippi** [comment]
@slainless in my local env!
Your first issue comes from esbuild, right?
