### ISSUE TITLE
Plugin breaks --watch option for bun

### ISSUE THREAD

**Issue by kirankunigiri** [ryoppippi/unplugin-typia#197]
After adding the plugin, `--watch` on bun no longer works. The project no longer restarts after saving/editing a file. This can be reproduced in the example project by running `bun run --watch index.ts`

**Comment by kirankunigiri** [comment]
Never mind, this is an issue with Bun itself. Any plugin will disable the --watch on Bun, which is pretty sad.
Related issue - https://github.com/oven-sh/bun/issues/4689

**Comment by ryoppippi** [comment]
Thank you for reporting!!
