### ISSUE TITLE
Wrong import in 0.6.1

### ISSUE THREAD

**Issue by dror-weiss** [ryoppippi/unplugin-typia#198]
Hi,

I'm getting an `esbuild error: ../../../node_modules/@ryoppippi/unplugin-typia/src/core/languages/svelte.js:13:56: Could not resolve "./svelte/compiler"`

It appears to originate from this line:
```
const { preprocess: sveltePreprocess } = await import('./svelte/compiler');
```

Shouldn't it be `await import('svelte/compiler')` ?

**Comment by ryoppippi** [comment]
@dror-weiss 
Hi!

You are right! Could you send us a PR?

**Comment by ryoppippi** [comment]
I got the same error btw.

**Comment by dror-weiss** [comment]
@ryoppippi , are you sure you have the correct version in JSR as this repo? It seems ok here but wrong there, so maybe just re-deploy.

**Comment by ryoppippi** [comment]
Oh, OK.
I'll release it soon

**Comment by ryoppippi** [comment]
@dror-weiss 
So, I found that JSR converts dynamic import automatically...
	const { preprocess: sveltePreprocess } = await import('./svelte/compiler');
	const { code } = await sveltePreprocess(source, {
		script: async ({ content, filename, attributes }) => {
			if (filename == null) {
				return { code: content };
			}

**Comment by ryoppippi** [comment]
@dror-weiss 
so the problem comes from
- JSR converts dynamic import into relative path import...(omg)
- JSR does not support peer dependency(https://github.com/jsr-io/jsr/issues/301)

So as a escape hatch, I decided to use jiti for dynamic import.

In my environment, it works. 
If it is okay for you, let me know and close this issue!

**Comment by ryoppippi** [comment]
I'll remove jiti and create wrapper of dynamic import

**Comment by dror-weiss** [comment]
@ryoppippi , thanks for all the effort! 0.6.4 does work for me.

That is so weird that JSR is changing the code, very unexpected. I wonder why you have to use dynamic import in the first place and not regular import.

Never the less we can close this as this issue is fixed.

**Comment by ryoppippi** [comment]
Because JSR does not support peerdependency, we need to use dynamic import.
We don't force people to install	Svelte as an dependency in e.g. React Project.
