### ISSUE TITLE
ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time

### ISSUE THREAD

**Issue by jasperdunn** [ryoppippi/unplugin-typia#212]
I'm getting this warning when adding `UnpluginTypia()` to my Remix project's `vite.config.ts` file:

```
(node:5784) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
```

It works, I'm just wondering if this is something to be concerned about.

**Comment by ryoppippi** [comment]
JSON import is used for caching, so it is not a critical issue
https://github.com/ryoppippi/unplugin-typia/blob/851b4ea7f413d9c92a75e019d075ab4c455563a4/packages/unplugin-typia/src/core/cache.ts#L5

However, some issues happens related to this import statement.
If you have any ideas to get the version of `Typia` safely without warning, please send us a PR.

**Comment by ryoppippi** [comment]
Maybe this issue is related https://github.com/nodejs/node/issues/51347

**Comment by ryoppippi** [comment]
I changed the way to parse `Typia`'s package.json
Please update the latest version of `unplugin-typia` and check the warning is wiped out

**Comment by jasperdunn** [comment]
Hey, I've been busy. I'll take a look over the weekend, thanks!

**Comment by ryoppippi** [comment]
Oops, OK! Thanks!!

**Comment by jasperdunn** [comment]
Seems to have worked, thanks!

**Comment by ryoppippi** [comment]
Cheers!!
