### ISSUE TITLE
Cannot read properties of undefined (reading '_formatError')

### ISSUE THREAD

**Issue by asnaeb** [ryoppippi/unplugin-typia#269]
### unplugin-typia version

0.6.16

### What platform is your computer?

Darwin 23.5.0 arm64 arm

### Describe the bug

When running Vite dev server with `vite` or a custom vite middleware, if any of the bundled files imports the package `typia`, this error is thrown. Building the app with `vite build` works and applies the transforms correctly.

### Reproduction

https://github.com/asnaeb/vite-unplugin-typia-repro

### Validations

- [x] Check that there isn't [already an issue](https://github.com/ryoppippi/unplugin-typia/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ryoppippi** [comment]
@asnaeb 
Hi!
Thank you for your report with a great repro repo!
I fixed the log function, and tsconfig option.

Update to the latest package and try it!

Also, it is good if you add `tsconfig` option when you use custom `tsconfig.json` (in this case `tsconfig.app.json`)
```ts
export default defineConfig({
  plugins: [
    UnpluginTypia({
      tsconfig: './tsconfig.app.json'
    }),
    react()
  ],
})
```

If these fixes solved this issue, feel free to close this issue.
Cheers

**Comment by asnaeb** [comment]
That was quick! 🥇 

I confirm that the issue is solved with the latest update.
