### ISSUE TITLE
feature request: tsconfig  alias path resolution

### ISSUE THREAD

**Issue by asnaeb** [ryoppippi/unplugin-typia#283]
### unplugin-typia version

0.6.18

### What platform is your computer?

Darwin 23.5.0 arm64 arm

### Describe the bug

When importing types from non relative paths, such types are parsed as `any`.  Example of non relative paths are paths relative to `tsconfig.compilerOptions.baseUrl` or paths mapped from `tsconfig.compilerOptions.paths`. 

Adding `resolve.alias` to `vite.config.ts` to map the paths in vite doesn't help.

### Reproduction

https://github.com/asnaeb/vite-unplugin-typia-repro

run with `npm run dev` and check the console.

### Validations

- [X] Check that there isn't [already an issue](https://github.com/ryoppippi/unplugin-typia/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ryoppippi** [comment]
Thank you for reporting this.
Currently, I'm not implementing alias resolution.
I thinks there is a two ways.
- `unplugin-typia` implements it
- `typia` implements it

Because `unplugin-typia` uses a lib called `pkg-types`, I'm waiting for [this issue](https://github.com/unjs/mlly/issues/271) solved

**Comment by ryoppippi** [comment]
I transfered this issue to typia's repo

**Comment by asnaeb** [comment]
> Thank you for reporting this. Currently, I'm not implementing alias resolution. Also, we don't implement for path resolution, so maybe `typia` compiler should implement it.

I tested typia without the plugin and code transformed directly with `typia generate` works for both cases

**Comment by ryoppippi** [comment]
Oh, really. Could you give me an example?

**Comment by ryoppippi** [comment]
OK, so `import {MyType} from "src/types/mytype";` is not appropriate for vite project. try use `./src/foo`

**Comment by asnaeb** [comment]
> Oh, really. Could you give me an example?

https://github.com/asnaeb/typia-test

- clone
- `npm install`
- `npm run build`
- inspect build directory

**Comment by ryoppippi** [comment]
I do not have time to do it, and actually I don't use alias so much, so your contribution are welcome

**Comment by ryoppippi** [comment]
Also, typia compiler resolve import statement here
https://github.com/samchon/typia/blob/master/src/transformers/ImportTransformer.ts#L4
https://github.com/samchon/typia/blob/aeb14afc631c49009c00d9659ee36a3f8a01d2ca/src/programmers/TypiaProgrammer.ts#L67

**Comment by ryoppippi** [comment]
Additionally, viye cannot handle those aliases in ts config.

**Comment by asnaeb** [comment]
I gave a quick look at it and seems like I've found a way to solve this without having to resolve anything from tsconfig but doing it the vite way: If non relative imports match something inside vite's `resolve.alias`, then imported types are resolved accordingly. I think this is the right way to handle this. If you agree, I'm going to write some tests and submit a PR tomorrow.
