### ISSUE TITLE
Very strange extraneous '}' at the end of the file preventing all compilation when added to vite

### ISSUE THREAD

**Issue by creikey** [ryoppippi/unplugin-typia#325]
### unplugin-typia version

latest

### What platform is your computer? Copy the output of `npx envinfo --system -npmPackages cleye --binaries`

macOS m3 MacBook Pro

### Describe the bug

No matter what's in any of the files, it's failing to build with a nonsensical stack trace pointing at text that doesn't exist in the file (unless I remove this plugin)

```
[plugin:vite:esbuild] Transform failed with 1 error:
/app/src/App.tsx:5:0: ERROR: Unexpected "}"
Unexpected "}"
3  |      return (<p>Hey</p>);
4  |  }
5  |  }
   |  ^
    at failureErrorWithLog (/app/node_modules/esbuild/lib/main.js:1472:15)
    at /app/node_modules/esbuild/lib/main.js:755:50
    at responseCallbacks.<computed> (/app/node_modules/esbuild/lib/main.js:622:9)
    at handleIncomingPacket (/app/node_modules/esbuild/lib/main.js:677:12)
    at Socket.readFromStdout (/app/node_modules/esbuild/lib/main.js:600:7)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at Pipe.onStreamRead (node:internal/stream_base_commons:191:23
```

### Reproduction

https://github.com/creikey/broken_typia

The bug occurs after `npm install && npx vite` and you try to connect to it, not in build which uses rollup (a different pipeline it seems)

This is happening in a larger project, and *no matter what* it's completely broken and nothing builds anymore. So I copied relevant files over to a smaller reproduction project and it's there.

I can't reproduce this in CI, it's really making me pull my hair out. But it happens locally on my computer, and *even in a docker* container ran on my computer the issue occurs. Just not in CI for some reason. Here I've uploaded the docker, if you get it loaded and run the container with `docker run -p 5173:5173 vite-project` then connect to the server, you should see the error *or else* somehow docker isn't even virtualizing whatever is wrong with my computer.

### Validations

- [X] Check that there isn't [already an issue](https://github.com/ryoppippi/unplugin-typia/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by creikey** [comment]
The docker image that reproduces the bug has been pushed to `docker.io/creikey/broken-unplugin-typia-vite` . It is as minimal as I can make it

**Comment by ryoppippi** [comment]
@creikey 
Thank you for your reporting, and this is wired.

I took a screen recording, so take a look at it
https://github.com/user-attachments/assets/af6692c7-c339-46ac-8225-d608209f61f2

**Comment by ryoppippi** [comment]
Also, when I edit your `App.tsx` and run `git diff`, the diff is like:
```diff
│  4 │     return (                                                  │  4 │     return (
│  5 │         <p>Hey</p>                                            │  5 │         <p>Hey</p>
│  6 │     );                                                        │  6 │     );
│  7 │-}                                                             │    │
\ No newline at end of file
```

So maybe this issue comes from your editor's config ?


OK, but when I disable `unplugin-typia`, it works. Hmm.

But in general, adding `\n` character at the end of the line solves the problem.
I'll investigate, but idk this issue comes from tsc or MagicString maybe?

**Comment by creikey** [comment]
Wow adding the `\n` at the end is great advice that does fix this issue, unfortunately I've been having nonstop build problems with typia and vite and now line numbers are completely broken in the frontend, and in an aws lambda the stack traces are all relative to the mjs file

**Comment by creikey** [comment]
Wow @ryoppippi  I've actually reproduced the bug here I think https://github.com/creikey/broken_typia_2 

but it has no lack of trailing newline. Let me know if you see it there too

**Comment by ryoppippi** [comment]
@creikey Thank you for your investigation.
And now, I found the solution!!! TADA~~

```diff
diff --git a/vite.config.ts b/vite.config.ts
index cce92a0..2ffa020 100644
--- a/vite.config.ts
+++ b/vite.config.ts
@@ -5,7 +5,7 @@ import react from '@vitejs/plugin-react'
 // https://vitejs.dev/config/
 export default defineConfig({
   plugins: [
-    react(),
     UnpluginTypia({}),
+    react(),
   ],
 })
```

Actually, idk why this solves the issue, but it works.

This should be included in the README.

First check that this fixes the problem in your environment.
If it does, please send me a PR so I can include it in the README.

**Comment by ryoppippi** [comment]
idk it is related to the trailing newline

**Comment by ryoppippi** [comment]
But changing plugin order doesn't solve the problem in https://github.com/creikey/broken_typia 🤔  
We still need to include the railing newline at the end. Hmm?

**Comment by creikey** [comment]
Moving unplugin typia to be before the react plugin does indeed allow it to successfully compile, however this means source mapping is torched and you can't debug or get good stack traces. You can reproduce like so:

<img width="885" alt="image" src="https://github.com/user-attachments/assets/693faa68-c033-493f-98ed-6225287b701a">

You can't set any breakpoints in the actual App.tsx file in my broken_typia_2 repo

**Comment by ryoppippi** [comment]
This is the issue of create sourcemap. Can you fix it?

**Comment by creikey** [comment]
I'm looking into it right now, I'm trying to write my own super simple typia vite plugin just to understand the process, currently I have

```typescript
import { transform as typiaTransform } from 'typia/lib/transform.js';
import ts from 'typescript';

export default function myPlugin() {
  return {
    name: 'transform-file',
    enforce: "pre",

    transform(src: any, id: string) {
      if(id.includes("node_modules")) return src;
      if(!(id.endsWith(".tsx") || id.endsWith(".ts"))) return src;
      const compilerOptions: ts.CompilerOptions = {
        target: ts.ScriptTarget.ES2020,
        module: ts.ModuleKind.ESNext,
        jsx: ts.JsxEmit.Preserve,
        strict: true,
        strictNullChecks: true,
      };
      const host = ts.createCompilerHost(compilerOptions);
      const program = ts.createProgram([id], compilerOptions, host);

      const transformer = typiaTransform(program, undefined, { addDiagnostic: (_: ts.Diagnostic) => 0 });
      
      const tsSource = program.getSourceFile(id);
      if(!tsSource) {
        throw new Error("Uh oh");
      }

      const transformResult = ts.transform(
          tsSource,
          [transformer],
          compilerOptions
      );
      const transformedFile = transformResult.transformed[0];

      if (transformedFile == null) {
        throw new Error('No file found');
      }
      const printer = ts.createPrinter();
      const transformedText = printer.printFile(transformedFile);
      console.log(`Filename: ${transformedFile.fileName}n\n------ Before -----\n\n${src}\n\n--------- After -----------\n\n${transformedText}\n\n`);
      return transformedText;
    },
  }
}
```

But for some reason the transformed doesn't have any typia transforms configured, so I'm trying to figure out why...

**Comment by creikey** [comment]
Honestly, this is taking way too long to figure out, I don't think typia works I'm just going to use sod

**Comment by ryoppippi** [comment]
@creikey I'm working on correcting sourcemap, but it takes time.
If you help me, please send a PR.
https://github.com/ryoppippi/unplugin-typia/tree/feature/fix-sourcemap

**Comment by ryoppippi** [comment]
@creikey I'm working on correcting sourcemap, but it takes time.
If you help me, please send a PR.
https://github.com/ryoppippi/unplugin-typia/tree/feature/fix-sourcemap

**Comment by creikey** [comment]
Interesting, it seems like a hard problem to preserve the source map across whatever modifications typia is doing (this seems important to me because without debugging/stack traces application development is substantially hampered) unfortunately I don't really have the time to help

**Comment by ryoppippi** [comment]
I'm about to fix it so wait a moment

**Comment by ryoppippi** [comment]
@creikey just published the new version, and this fixes the sorcemap issue.
Please check it out.
https://github.com/ryoppippi/unplugin-typia/releases/tag/v1.0.4

**Comment by ryoppippi** [comment]
@creikey Hi! Have you ever checked this?

**Comment by creikey** [comment]
No sorry I removed all references to typia in my project and permanently moved from it
