### ISSUE TITLE
Count number of downloads from `jsr.io`

### ISSUE THREAD

**Issue by samchon** [ryoppippi/unplugin-typia#332]
Current `unplugin-typia` repo is showing only `npmjs.com` downloads.

By the way, the `unplugin-typia` started from the `jsr.io` package, and `npmjs` was later.

Therefore, many `unplugin-typia` users may misunderstand. The download count needs to be updated.

**Comment by ryoppippi** [comment]
Hi @samchon 
What does download number refer to?
I think there are both npm and jsr in the README.
There is no way to display the Download number for jsr at present.
The npm Downlod number is displayed.

**Comment by samchon** [comment]
Oh my god, `jsr.io` is not supporting the number of downloads statistics.

**Comment by ryoppippi** [comment]
Yeah, so we cannot deal with that.
So I close this for now.
