### ISSUE TITLE
BUG(Next.js): types are imported as `any` when using path alias

### ISSUE THREAD

**Issue by hambergerpls** [ryoppippi/unplugin-typia#338]
### unplugin-typia version

1.0.6

### What platform is your computer? Copy the output of `npx envinfo --system -npmPackages cleye --binaries`

  System:     OS: Linux 5.15 NixOS 24.05 (Uakari) 24.05 (Uakari)     CPU: (8) x64 AMD Ryzen 7 5800H with Radeon Graphics     Memory: 58.30 GB / 62.66 GB     Container: Yes     Shell: 5.9 - /run/current-system/sw/bin/zsh   Binaries:     Node: 20.17.0 - /nix/store/dcdc33kdjdhjnzg6rkmd0cx4kpwl8cac-nodejs-20.17.0/bin/node     npm: 10.8.2 - /nix/store/dcdc33kdjdhjnzg6rkmd0cx4kpwl8cac-nodejs-20.17.0/bin/npm     pnpm: 9.12.1 - /nix/store/8p5d95fq1rnm6pvdad2kv1cfij0bydch-pnpm-9.12.1/bin/pnpm     bun: 1.1.29 - /nix/store/1xgl28bhcsvmw14vfyxlrb5qhmlzjifi-bun-1.1.29/bin/bun

### Describe the bug

The Next.js [example](https://github.com/ryoppippi/unplugin-typia/tree/main/examples/nextjs) works when importing types using [relative paths](https://github.com/ryoppippi/unplugin-typia/blob/9877201c8e456f25c2656a9eebd00b53537cfda3/examples/nextjs/app/RandomData/index.tsx#L2) `./actions`.

If the import path is changed to alias path `@/app/RandomData/actions`, the type is imported as `any`

This also prevents other functions from executing properly. (e.g. `typia.validate(), typia.random()`)

### Reproduction

1. Change the import path of types from relative `./actions` to alias path `@/app/RandomData/actions` in Next.js example
2. Random data cannot be generated.

### Validations

- [X] Check that there isn't [already an issue](https://github.com/ryoppippi/unplugin-typia/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hambergerpls** [comment]
I have found cause of the problem. Please review #339 @ryoppippi

**Comment by ryoppippi** [comment]
SO looks like relative/absolute path issue.
I got it. thanks
